### ISSUE TITLE
"splice" function output only as list

### ISSUE THREAD

**Issue by FedeMassetti** [pierreroudier/spectacles#1]
When using splice(x) the resulting output is an object of class "list" containing an object of the same class as x

e.g. from the splice example
```
data(australia)
spectra(australia) <- sr_no ~ ... ~ 350:2500
oz_spliced <- splice(australia)
#this will result in a "large list" containing my spectra
oz_spliced2 <- oz_spliced[[1]]
#this gave me the object I think was supposed to be the output
```

In addition the splice in the output doesn't seem to be corrected compared to the original

**Comment by FedeMassetti** [comment]
I think I found the problem. The package has some clash with the tidyverse package. Loading spectacles AFTER tidyverse seems to solve the problem giving just this warning

> Attaching package: ‘spectacles’

The following object is masked from ‘package:purrr’:

    splice

The following object is masked from ‘package:tidyr’:

    separate

**Comment by pierreroudier** [comment]
@FedeMassetti  thanks for the bug report --- indeed `splice` is exported from the `tidyr` namespace, os if you loaded `tidyr` *after* `spectacles`, you will need to specify the namespace explicitely using `::`:

```
library(spectacles)
data(australia)
spectra(australia) <- sr_no ~ ... ~ 350:2500
oz_spliced <- splice(australia)
oz_splice
```
