### ISSUE TITLE
splice

### ISSUE THREAD

**Issue by aloboa** [pierreroudier/spectacles#7]
According to the splice help page,
"This is the correction method available in the ViewSpec Pro software from ASD"

The documentation for the splice correction in ViewSpec actually states:
"This is usually done only for presentations and documentation or when using the data to match against
a spectral library, it is not meant to correct the data."

I am confused by this final recommendation. Does it hold for spectacles::splice() as well? I see all spectra with "no steps"...

**Comment by pierreroudier** [comment]
This confuses me too, to be honest, given the splice correction harmonises issues that can come up with variations in the sensor's temperature. I always use it as pre-processing prior to modelling.
